steps:
- name: node:18.15.0
  - name: "gcr.io/cloud-builders/yarn"
    args: ["add"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "1600s" 
options:
  logging: CLOUD_LOGGING_ONLY
